default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV["matiasghf"] %>  # Add your PostgreSQL username
  password: <%= ENV["matias.99"] %>  # Add your PostgreSQL password
  host: localhost                      # Host for PostgreSQL
  port: 5432                           # Default port for PostgreSQL

development:
  <<: *default
  database: bmp_project_development

test:
  <<: *default
  database: bmp_project_test

production:
  <<: *default
  database: bmp_project_production
  username: bmp_project                 # Use your production database username
  password: <%= ENV["BMP_PROJECT_DATABASE_PASSWORD"] %>
